### ISSUE TITLE
why there is  no O mouth sprite , 

### ISSUE THREAD

**Issue by stickylabdev** [crdrury/Unity-Rhubarb-Lip-Syncer#1]
movements,, i need the o

**Comment by crdrury** [comment]
Hi!

The letter names of the mouth shapes don't represent the sound made by the shape. The 'O' mouth would be created with the E and F mouth shapes.

See [the Rhubarb list of mouth shapes](https://github.com/DanielSWolf/rhubarb-lip-sync#user-content-mouth-shapes) for an explanation of which shapes go with which sounds.

**Comment by stickylabdev** [comment]
Could you please make another example for cartoon sprites    ... I need
another example  .... Thats will make me more understand. Please

Pada tanggal Rab, 7 Apr 2021 05.42, crdrury ***@***.***>
menulis:

**Comment by crdrury** [comment]
Unfortunately I designed this with 3D models in mind, so there isn't really any support for 2D sprites in this version. I'll start looking into the 2D side of things this week and see if I can get a new update out as soon as possible!

**Comment by stickylabdev** [comment]
Sounds good, thanks!

Ineed smooth mouth Transition movements. That will helped me alot... I also
keep try and error

Pada tanggal Sel, 13 Apr 2021 08.12, crdrury ***@***.***>
menulis:

**Comment by crdrury** [comment]
Hi! I've put up a new version of the code that has scripts for 2D animations. Once you have the new scripts and Rhubarb installed, [this video](https://www.youtube.com/watch?v=V2-M-fjaJcs) goes through how to use the scripts in Unity.

**Comment by stickylabdev** [comment]
Awesome, thanks for the update!

Pada tanggal Sen, 26 Apr 2021 03.38, crdrury ***@***.***>
menulis:
