### ISSUE TITLE
how to set for diferent language

### ISSUE THREAD

**Issue by stickylabdev** [crdrury/Unity-Rhubarb-Lip-Syncer#2]
indonesian language

**Comment by stickylabdev** [comment]
the mouth should moves diferent right

**Comment by crdrury** [comment]
Hi!

I just put up a new version with some more options in the editor. For non-English speech, make sure the "Phonetic" checkbox is checked.

The difference between the two is explained [here](https://github.com/DanielSWolf/rhubarb-lip-sync#Recognizers) if you want to know what Rhubarb is doing in the background.

**Comment by stickylabdev** [comment]
This is what i looking for. Thanks

Pada tanggal Kam, 24 Jun 2021 07.08, crdrury ***@***.***>
menulis:
