### ISSUE TITLE
when i click analyze audio i dont get the phonem list text :(

### ISSUE THREAD

**Issue by stickylabdev** [crdrury/Unity-Rhubarb-Lip-Syncer#3]
![image](https://user-images.githubusercontent.com/13078369/127279648-7ab255ab-b003-408c-a759-43ac30e5f1c7.png)

**Comment by stickylabdev** [comment]
got new error


FileNotFoundException: Assets/Unity-Rhubarb-Lip-Syncer/Animations/Resources/HiGuys - Mouth Shapes.txt does not exist

**Comment by crdrury** [comment]
Hi!

I originally had the script looking for /Animations, and /Audio directly inside of the Assets folder, but it could make sense to keep everything in its own folder like you did. I just pushed a new version which should work with either setup.
