### ISSUE TITLE
Occur "[Fatal] Application terminating with error : Error Processing file." but it is hard to find out what's the matter

### ISSUE THREAD

**Issue by Fareastsolar** [crdrury/Unity-Rhubarb-Lip-Syncer#4]
Really helpful program and video it is. However, I have some trouble doing this on my own pc. I follow every steps. but when I press button "Analyze Audio And Generate Animation" on Unity3D it says "[Fatal] Application terminating with error : Error Processing file Assets/Audio/Resources/mysoundname.ogg, Error performing speech recognition via PocketSphinx tools. Could not determine path of bin Directory. ~~" like this. I checked sound file formation and directory(Assets/Audio/Resources) about a hundred times.(I mean It doesn't seems like the matter. sound file is Vorvis, 22050Hz, Mono, ogg file. and save in the Assets/Audio/Resources folder) what is the problem do you think please check this message. (error window capture posted below
![error window](https://user-images.githubusercontent.com/110531846/183109102-29a50920-91d3-4b02-884e-cd3d512fac54.jpg)
)

**Comment by crdrury** [comment]
Hi!

This error message is actually coming from [Rhubarb Lip Sync](https://github.com/DanielSWolf/rhubarb-lip-sync) which my project is basically just a Unity wrapper for. Looking at their code, my guess is the Rhubarb installation got changed around on your computer, maybe rhubarb.exe got moved out of the main folder. It looks like for it to work the Rhubarb folder needs to be structured like this:

![image](https://user-images.githubusercontent.com/39220609/183787076-e7447665-1b2d-40eb-a476-ee2f87cd21d5.png)

I'd start by checking that folder and making sure everything is the same as when it was installed

**Comment by Fareastsolar** [comment]
Thank you. I resolve this problem finally. You are right. It was a directory problem. I downloaded the file and saved as "Rhubarb-Lip-Sync-1.13.0-Windows" and unziped the folder name as it was. now I changed the folder name as "Rhubarb_Lip_Sync_1_13_0_Windows" and adjust PATH route. And it works! finally. Thank you for your kind answer indeed. have a nice day crdrury.

**Comment by e-lifee** [comment]
> Thank you. I resolve this problem finally. You are right. It was a directory problem. I downloaded the file and saved as "Rhubarb-Lip-Sync-1.13.0-Windows" and unziped the folder name as it was. now I changed the folder name as "Rhubarb_Lip_Sync_1_13_0_Windows" and adjust PATH route. And it works! finally. Thank you for your kind answer indeed. have a nice day crdrury.

hey, I am facing with the same problem. I tried your solution but it's still the same. do you have any other advice?
